<a href="https://colab.research.google.com/github/RashmitVartak/DAV/blob/main/DAV_exp1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Experiment - 1: Getting introduced to data analytics libraries in Python and R**



Name:Rashmit Vartak

Div: D11AD

Rollno:63



**Title of Experiment**:Getting introduced to data analytics libraries in Python and R

**Outcome of Experiment :**
To Identify and Explore various data analytics Libraries in R and Python.
Performed simple experiments with these libraries in Python and R.

**Theory :**
Python and R are two widely used programming languages in the field of data analysis and visualization, each with its own strengths and capabilities. Both languages provide extensive libraries and tools that make them popular choices for handling and analyzing data.

Python is renowned for its simplicity and readability, making it an excellent choice for data analysis tasks.
1)The Pandas library in Python is a powerful tool for data manipulation and analysis, offering data structures like DataFrames that facilitate easy handling of tabular data.

2)Numpy is another essential library that provides support for large, multi-dimensional arrays and matrices, along with mathematical functions to operate on these arrays efficiently.
These libraries, combined with others like Matplotlib and Seaborn for visualization, create a comprehensive ecosystem for data analysis and visualization in Python.

On the other hand, R is a statistical programming language that excels in statistical analysis and graphics.
 1)The stringr package in R is particularly useful for string manipulation tasks, providing functions for pattern matching, substring extraction, and other string-related operations.

2)The jsonlite package is handy for working with JSON data, allowing easy conversion between JSON and R data structures.
 R's ggplot2 package is a powerful tool for creating sophisticated and customizable data visualizations, making it a favorite among statisticians and data scientists.


**Exploration of Python and R libraries**


**1.  Top 5 Data Analytics Libraries in Python**

*   NumPy

NumPy is the fundamental package for scientific computing in Python.
It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


*   Pandas

pandas is a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive
Fast and efficient DataFrame object with default and customized indexing.
Tools for loading data into in-memory data objects from different file formats.
Data alignment and integrated handling of missing data.
High performance merging and joining of data.

*   Scikit-Learn

Scikit-learn is an open source machine learning library that supports supervised and unsupervised learning. It also provides various tools for model fitting, data preprocessing, model selection, model evaluation, and many other utilities.
It provides a selection of efficient tools for machine learning and statistical modeling including classification, regression, clustering and dimensionality reduction via a consistence interface in Python.

*   Keras

Keras is a popular library that is used extensively for deep learning and neural network modules.
Keras runs on top of open source machine libraries like TensorFlow, Theano or Cognitive Toolkit (CNTK)
Keras supports both the TensorFlow and Theano backends, so it is a good option if you don't want to dive into the details of TensorFlow.

*   BeautifulSoup

Beautiful Soup is a Python package for parsing HTML and XML documents.
It creates a parse tree for parsed pages that can be used to extract data from HTML, which is useful for web scraping.

**2.
Top 5 Data Analytics Libraries in R**


*   dplyr

The dplyr is a powerful R-package to manipulate, clean and summarize unstructured data.
It makes data exploration and data manipulation easy and fast in R. The package "dplyr" comprises many functions that perform mostly used data manipulation operations such as applying filter, selecting specific columns, sorting data, adding or deleting columns and aggregating data.




*   ggplot2


ggplot2 implements the grammar of graphics, a coherent system for describing and building graphs.
This approach gives us a coherent way to produce visualizations by expressing relationships between the attributes of data and their graphical representation
Thus, one can create plots faster by learning one system and applying it in many places.
*   shiny

Shiny is an R package that makes it easy to build interactive web applications (apps) straight from R.
Shiny is a framework for creating web applications using R code.
It is designed primarily with data scientists in mind and it can create pretty complicated Shiny apps without requiring knowledge of HTML, CSS, or JavaScript
Provides a carefully curated set of user interface (UI for short) functions that generate the HTML, CSS, and JavaScript needed for common tasks
It follows a style of programming called reactive programming which automatically tracks the dependencies of pieces of code.


*   lubridate

R by default offers limited capability to deal with date and time.
Lubridate is an R package that makes it easier to work with dates and times
It offers a wide variety of functions that make it easier to work with .dates and time.


# Python

**Importing the Libraries of Python**

**Exploring 2 libraries in it**

In [ ]:
import pandas as pd
import numpy as np


1)Numpy

In [ ]:
#creating 2d array using arrange function
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a.shape

(3, 3)

In [ ]:
#creating 2d array using array function
b = np.array([(1,2),(8,9),(3,4),(10,11)])
b

array([[ 1,  2],
       [ 8,  9],
       [ 3,  4],
       [10, 11]])

In [ ]:
b.shape

(4, 2)

In [ ]:
b.dtype.name

'int64'

In [ ]:
b.size

8

In [ ]:
#3d array
c = np.arange(18).reshape(3,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [ ]:
arr = np.array([1.23,3.12,1.73,0.68999,4.200])
arr.dtype.name

'float64'

In [ ]:
A = np.arange(4).reshape(2,2)
print("Original Matrix")
print(A)
z=4
d = A*z
print("Matrix after multiplication")
print(d)

Original Matrix
[[0 1]
 [2 3]]
Matrix after multiplication
[[ 0  4]
 [ 8 12]]


In [ ]:
B= np.arange(5,9,).reshape(2,2)
B

array([[5, 6],
       [7, 8]])

In [ ]:
C = A @ B
print(C)

[[ 7  8]
 [31 36]]


In [ ]:
D = np.array([1,2,3,4,5,6,7,8,9,10])
print("Slicing")
print(D[2:9:2])
print("Addition")
D+=5
print(D)
print("Square Root")
print(D**0.5)
D**2
print("Changing the shape of Array")
newD=D.reshape(2,5)
print(newD)
print("Transposing")
print(newD.T)

Slicing
[3 5 7 9]
Addition
CHanging
[ 6  7  8  9 10 11 12 13 14 15]
Square Root
[2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335]
Changing the shape of Array
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
Transposing
[[ 6 11]
 [ 7 12]
 [ 8 13]
 [ 9 14]
 [10 15]]


2)Pandas

In [ ]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
 df2 = pd.DataFrame(
      {
       "A": 1.0,
       "B": pd.Timestamp("20130102"),
       "C": pd.Series(1, index=list(range(4)), dtype="float32"),
       "D": np.array([3] * 4, dtype="int32"),
       "E": pd.Categorical(["test", "train", "test", "train"]),
       "F": "foo",
      }
 )
 df2
 df2.dtypes


A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [ ]:
dates = pd.date_range("20130101", periods=25)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16',
               '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20',
               '2013-01-21', '2013-01-22', '2013-01-23', '2013-01-24',
               '2013-01-25'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(25, 5), index=dates, columns=list("ABCDE"))
df

A         B         C         D         E
2013-01-01  0.107576  0.750734  0.185972  0.476068  0.605057
2013-01-02 -0.573314 -1.350082  0.342563 -1.588528 -0.054458
2013-01-03 -0.153008 -0.467943  0.255162  0.647887 -1.311899
2013-01-04  1.091488  1.207294  0.507226 -1.510210  1.256918
2013-01-05 -0.140795  2.017113 -0.308425 -0.585616 -0.412642
2013-01-06  1.052367  0.011832  0.475134  1.446361 -1.306383
2013-01-07 -1.342726  0.438657  0.582202 -2.113504  1.655421
2013-01-08 -1.189645  0.275313  0.529499 -0.408756  0.697636
2013-01-09  0.220678  1.521160 -0.515815  1.216148  1.226532
2013-01-10  0.668727 -1.091675 -0.501773  0.864345  1.076853
2013-01-11  0.568564 -0.974728  3.123097  2.548139  0.900564
2013-01-12 -1.218460 -0.626399  0.428790  0.160845 -0.548774
2013-01-13 -0.058406 -0.200156 -1.435979 -0.784211  1.204111
2013-01-14  0.369317  0.170668 -0.483159  0.016866  0.867944
2013-01-15 -0.230533 -0.588282 -0.348039 -1.663274 -1.239653
2013-01-16 -0.364337  0.006349 -0.778211  0.794382  0.749732
2013-01-17 -1.074476 -0.759358  0.089320  0.329675 -0.318578
2013-01-18  0.012460 -0.366088  0.352593 -1.765442  0.375206
2013-01-19 -0.830587 -0.466824 -2.063527 -0.298426  0.648740
2013-01-20 -0.331877  0.953242 -0.945732 -1.777833  0.107342
2013-01-21  0.484314 -0.195491 -0.579125 -0.767967 -0.751173
2013-01-22  0.352269  1.428700  0.987922  1.366497 -0.135692
2013-01-23 -0.893382  1.798994 -1.020458 -0.693708  0.307356
2013-01-24  0.847835 -1.021172  0.245797  0.403497 -0.455116
2013-01-25  1.550033 -1.184921  1.899368  0.815398  0.140992

In [ ]:
df.describe()

A          B          C          D          E
count  25.000000  25.000000  25.000000  25.000000  25.000000
mean   -0.043037   0.051477   0.040976  -0.114855   0.211441
std     0.783065   0.983129   1.043947   1.210865   0.849346
min    -1.342726  -1.350082  -2.063527  -2.113504  -1.311899
25%    -0.573314  -0.626399  -0.515815  -0.784211  -0.412642
50%    -0.058406  -0.195491   0.185972   0.016866   0.307356
75%     0.484314   0.750734   0.475134   0.794382   0.867944
max     1.550033   2.017113   3.123097   2.548139   1.655421

In [ ]:
df.head(5)
df.tail(5)

A         B         C         D         E
2013-01-21  0.484314 -0.195491 -0.579125 -0.767967 -0.751173
2013-01-22  0.352269  1.428700  0.987922  1.366497 -0.135692
2013-01-23 -0.893382  1.798994 -1.020458 -0.693708  0.307356
2013-01-24  0.847835 -1.021172  0.245797  0.403497 -0.455116
2013-01-25  1.550033 -1.184921  1.899368  0.815398  0.140992

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 25 entries, 2013-01-01 to 2013-01-25
Freq: D
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       25 non-null     float64
 1   B       25 non-null     float64
 2   C       25 non-null     float64
 3   D       25 non-null     float64
 4   E       25 non-null     float64
dtypes: float64(5)
memory usage: 1.2 KB


In [ ]:
df.sort_values("B")

A         B         C         D         E
2013-01-02 -0.573314 -1.350082  0.342563 -1.588528 -0.054458
2013-01-25  1.550033 -1.184921  1.899368  0.815398  0.140992
2013-01-10  0.668727 -1.091675 -0.501773  0.864345  1.076853
2013-01-24  0.847835 -1.021172  0.245797  0.403497 -0.455116
2013-01-11  0.568564 -0.974728  3.123097  2.548139  0.900564
2013-01-17 -1.074476 -0.759358  0.089320  0.329675 -0.318578
2013-01-12 -1.218460 -0.626399  0.428790  0.160845 -0.548774
2013-01-15 -0.230533 -0.588282 -0.348039 -1.663274 -1.239653
2013-01-03 -0.153008 -0.467943  0.255162  0.647887 -1.311899
2013-01-19 -0.830587 -0.466824 -2.063527 -0.298426  0.648740
2013-01-18  0.012460 -0.366088  0.352593 -1.765442  0.375206
2013-01-13 -0.058406 -0.200156 -1.435979 -0.784211  1.204111
2013-01-21  0.484314 -0.195491 -0.579125 -0.767967 -0.751173
2013-01-16 -0.364337  0.006349 -0.778211  0.794382  0.749732
2013-01-06  1.052367  0.011832  0.475134  1.446361 -1.306383
2013-01-14  0.369317  0.170668 -0.483159  0.016866  0.867944
2013-01-08 -1.189645  0.275313  0.529499 -0.408756  0.697636
2013-01-07 -1.342726  0.438657  0.582202 -2.113504  1.655421
2013-01-01  0.107576  0.750734  0.185972  0.476068  0.605057
2013-01-20 -0.331877  0.953242 -0.945732 -1.777833  0.107342
2013-01-04  1.091488  1.207294  0.507226 -1.510210  1.256918
2013-01-22  0.352269  1.428700  0.987922  1.366497 -0.135692
2013-01-09  0.220678  1.521160 -0.515815  1.216148  1.226532
2013-01-23 -0.893382  1.798994 -1.020458 -0.693708  0.307356
2013-01-05 -0.140795  2.017113 -0.308425 -0.585616 -0.412642

In [ ]:
df["D"]

2013-01-01    0.476068
2013-01-02   -1.588528
2013-01-03    0.647887
2013-01-04   -1.510210
2013-01-05   -0.585616
2013-01-06    1.446361
2013-01-07   -2.113504
2013-01-08   -0.408756
2013-01-09    1.216148
2013-01-10    0.864345
2013-01-11    2.548139
2013-01-12    0.160845
2013-01-13   -0.784211
2013-01-14    0.016866
2013-01-15   -1.663274
2013-01-16    0.794382
2013-01-17    0.329675
2013-01-18   -1.765442
2013-01-19   -0.298426
2013-01-20   -1.777833
2013-01-21   -0.767967
2013-01-22    1.366497
2013-01-23   -0.693708
2013-01-24    0.403497
2013-01-25    0.815398
Freq: D, Name: D, dtype: float64

In [ ]:
df[0:24:6]

A         B         C         D         E
2013-01-01  0.107576  0.750734  0.185972  0.476068  0.605057
2013-01-07 -1.342726  0.438657  0.582202 -2.113504  1.655421
2013-01-13 -0.058406 -0.200156 -1.435979 -0.784211  1.204111
2013-01-19 -0.830587 -0.466824 -2.063527 -0.298426  0.648740

# **R**

**Importing the Libraries of R**

**Exploring 2 libraries in it**

In [9]:
install.packages("stringr")
library(stringr)
install.packages("jsonlite")
library(jsonlite)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [4]:
str_length("RASHMIT")

[1] 7

In [5]:
x <- c("RASHMIT", "VARTAK")
str_sub(x, 5, 2)

str_pad(x, 10)

[1] "" ""

[1] "   RASHMIT" "    VARTAK"

In [6]:
x <- "My name is Rashmit Vartak."
str_to_upper(x)
str_to_title(x)
str_to_lower(x)

[1] "MY NAME IS RASHMIT VARTAK."

[1] "My Name Is Rashmit Vartak."

[1] "my name is rashmit vartak."

In [7]:
x <- c("y", "i", "k")
str_order(x)

str_sort(x)

[1] 2 3 1

[1] "i" "k" "y"

In [8]:
str_split("a-b-c", "-")

str_split_fixed("a-b-c", "-", n = 2)

[[1]]
[1] "a" "b" "c"

[,1] [,2]
[1,] a    b-c

In [10]:
json <- '["Mario", "Peach", null, "Bowser"]'

fromJSON(json)

[1] "Mario"  "Peach"  NA       "Bowser"

In [11]:
json <-
'[
  {"Name" : "Mario", "Age" : 32, "Occupation" : "Plumber"},
  {"Name" : "Peach", "Age" : 21, "Occupation" : "Princess"},
  {},
  {"Name" : "Bowser", "Occupation" : "Koopa"}
]'
mydf <- fromJSON(json)
mydf

Name   Age Occupation
1 Mario  32  Plumber   
2 Peach  21  Princess  
3 NA     NA  NA        
4 Bowser NA  Koopa

In [12]:
mydf$Ranking <- c(3, 1, 2, 4)
toJSON(mydf, pretty=TRUE)

[
  {
    "Name": "Mario",
    "Age": 32,
    "Occupation": "Plumber",
    "Ranking": 3
  },
  {
    "Name": "Peach",
    "Age": 21,
    "Occupation": "Princess",
    "Ranking": 1
  },
  {
    "Ranking": 2
  },
  {
    "Name": "Bowser",
    "Occupation": "Koopa",
    "Ranking": 4
  }
] 

In [13]:
json <- '[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
]'
mymatrix <- fromJSON(json)
mymatrix

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [14]:
toJSON(mymatrix, pretty = TRUE)


[
  [1, 2, 3, 4],
  [5, 6, 7, 8],
  [9, 10, 11, 12]
] 