# **PYTHON**

Importing the Libraries

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras as k


1)Numpy

In [29]:
#creating 2d array using arrange function
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
a.shape

(3, 3)

In [19]:
#creating 2d array using array function
b = np.array([(1,2),(8,9),(3,4),(10,11)])
b

array([[ 1,  2],
       [ 8,  9],
       [ 3,  4],
       [10, 11]])

In [21]:
b.shape

(4, 2)

In [27]:
b.dtype.name

'int64'

In [30]:
b.size

8

In [26]:
#3d array
c = np.arange(18).reshape(3,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [36]:
arr = np.array([1.23,3.12,1.73,0.68999,4.200])
arr.dtype.name

'float64'

In [47]:
A = np.arange(4).reshape(2,2)
print("Original Matrix")
print(A)
z=4
d = A*z
print("Matrix after multiplication")
print(d)

Original Matrix
[[0 1]
 [2 3]]
Matrix after multiplication
[[ 0  4]
 [ 8 12]]


In [48]:
B= np.arange(5,9,).reshape(2,2)
B

array([[5, 6],
       [7, 8]])

In [49]:
C = A @ B
print(C)

[[ 7  8]
 [31 36]]


In [69]:
D = np.array([1,2,3,4,5,6,7,8,9,10])
print("Slicing")
print(D[2:9:2])
print("Addition")
D+=5
print(D)
print("Square Root")
print(D**0.5)
D**2
print("Changing the shape of Array")
newD=D.reshape(2,5)
print(newD)
print("Transposing")
print(newD.T)

Slicing
[3 5 7 9]
Addition
CHanging
[ 6  7  8  9 10 11 12 13 14 15]
Square Root
[2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162 3.60555128 3.74165739 3.87298335]
Changing the shape of Array
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
Transposing
[[ 6 11]
 [ 7 12]
 [ 8 13]
 [ 9 14]
 [10 15]]


2)Pandas

In [90]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [95]:
 df2 = pd.DataFrame(
      {
       "A": 1.0,
       "B": pd.Timestamp("20130102"),
       "C": pd.Series(1, index=list(range(4)), dtype="float32"),
       "D": np.array([3] * 4, dtype="int32"),
       "E": pd.Categorical(["test", "train", "test", "train"]),
       "F": "foo",
      }
 )
 df2
 df2.dtypes


A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [96]:
dates = pd.date_range("20130101", periods=25)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08',
               '2013-01-09', '2013-01-10', '2013-01-11', '2013-01-12',
               '2013-01-13', '2013-01-14', '2013-01-15', '2013-01-16',
               '2013-01-17', '2013-01-18', '2013-01-19', '2013-01-20',
               '2013-01-21', '2013-01-22', '2013-01-23', '2013-01-24',
               '2013-01-25'],
              dtype='datetime64[ns]', freq='D')

In [98]:
df = pd.DataFrame(np.random.randn(25, 5), index=dates, columns=list("ABCDE"))
df

A         B         C         D         E
2013-01-01  0.107576  0.750734  0.185972  0.476068  0.605057
2013-01-02 -0.573314 -1.350082  0.342563 -1.588528 -0.054458
2013-01-03 -0.153008 -0.467943  0.255162  0.647887 -1.311899
2013-01-04  1.091488  1.207294  0.507226 -1.510210  1.256918
2013-01-05 -0.140795  2.017113 -0.308425 -0.585616 -0.412642
2013-01-06  1.052367  0.011832  0.475134  1.446361 -1.306383
2013-01-07 -1.342726  0.438657  0.582202 -2.113504  1.655421
2013-01-08 -1.189645  0.275313  0.529499 -0.408756  0.697636
2013-01-09  0.220678  1.521160 -0.515815  1.216148  1.226532
2013-01-10  0.668727 -1.091675 -0.501773  0.864345  1.076853
2013-01-11  0.568564 -0.974728  3.123097  2.548139  0.900564
2013-01-12 -1.218460 -0.626399  0.428790  0.160845 -0.548774
2013-01-13 -0.058406 -0.200156 -1.435979 -0.784211  1.204111
2013-01-14  0.369317  0.170668 -0.483159  0.016866  0.867944
2013-01-15 -0.230533 -0.588282 -0.348039 -1.663274 -1.239653
2013-01-16 -0.364337  0.006349 -0.778211  0.794382  0.749732
2013-01-17 -1.074476 -0.759358  0.089320  0.329675 -0.318578
2013-01-18  0.012460 -0.366088  0.352593 -1.765442  0.375206
2013-01-19 -0.830587 -0.466824 -2.063527 -0.298426  0.648740
2013-01-20 -0.331877  0.953242 -0.945732 -1.777833  0.107342
2013-01-21  0.484314 -0.195491 -0.579125 -0.767967 -0.751173
2013-01-22  0.352269  1.428700  0.987922  1.366497 -0.135692
2013-01-23 -0.893382  1.798994 -1.020458 -0.693708  0.307356
2013-01-24  0.847835 -1.021172  0.245797  0.403497 -0.455116
2013-01-25  1.550033 -1.184921  1.899368  0.815398  0.140992

In [99]:
df.describe()

A          B          C          D          E
count  25.000000  25.000000  25.000000  25.000000  25.000000
mean   -0.043037   0.051477   0.040976  -0.114855   0.211441
std     0.783065   0.983129   1.043947   1.210865   0.849346
min    -1.342726  -1.350082  -2.063527  -2.113504  -1.311899
25%    -0.573314  -0.626399  -0.515815  -0.784211  -0.412642
50%    -0.058406  -0.195491   0.185972   0.016866   0.307356
75%     0.484314   0.750734   0.475134   0.794382   0.867944
max     1.550033   2.017113   3.123097   2.548139   1.655421

In [100]:
df.head(5)
df.tail(5)

A         B         C         D         E
2013-01-21  0.484314 -0.195491 -0.579125 -0.767967 -0.751173
2013-01-22  0.352269  1.428700  0.987922  1.366497 -0.135692
2013-01-23 -0.893382  1.798994 -1.020458 -0.693708  0.307356
2013-01-24  0.847835 -1.021172  0.245797  0.403497 -0.455116
2013-01-25  1.550033 -1.184921  1.899368  0.815398  0.140992

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 25 entries, 2013-01-01 to 2013-01-25
Freq: D
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       25 non-null     float64
 1   B       25 non-null     float64
 2   C       25 non-null     float64
 3   D       25 non-null     float64
 4   E       25 non-null     float64
dtypes: float64(5)
memory usage: 1.2 KB


In [103]:
df.sort_values("B")

A         B         C         D         E
2013-01-02 -0.573314 -1.350082  0.342563 -1.588528 -0.054458
2013-01-25  1.550033 -1.184921  1.899368  0.815398  0.140992
2013-01-10  0.668727 -1.091675 -0.501773  0.864345  1.076853
2013-01-24  0.847835 -1.021172  0.245797  0.403497 -0.455116
2013-01-11  0.568564 -0.974728  3.123097  2.548139  0.900564
2013-01-17 -1.074476 -0.759358  0.089320  0.329675 -0.318578
2013-01-12 -1.218460 -0.626399  0.428790  0.160845 -0.548774
2013-01-15 -0.230533 -0.588282 -0.348039 -1.663274 -1.239653
2013-01-03 -0.153008 -0.467943  0.255162  0.647887 -1.311899
2013-01-19 -0.830587 -0.466824 -2.063527 -0.298426  0.648740
2013-01-18  0.012460 -0.366088  0.352593 -1.765442  0.375206
2013-01-13 -0.058406 -0.200156 -1.435979 -0.784211  1.204111
2013-01-21  0.484314 -0.195491 -0.579125 -0.767967 -0.751173
2013-01-16 -0.364337  0.006349 -0.778211  0.794382  0.749732
2013-01-06  1.052367  0.011832  0.475134  1.446361 -1.306383
2013-01-14  0.369317  0.170668 -0.483159  0.016866  0.867944
2013-01-08 -1.189645  0.275313  0.529499 -0.408756  0.697636
2013-01-07 -1.342726  0.438657  0.582202 -2.113504  1.655421
2013-01-01  0.107576  0.750734  0.185972  0.476068  0.605057
2013-01-20 -0.331877  0.953242 -0.945732 -1.777833  0.107342
2013-01-04  1.091488  1.207294  0.507226 -1.510210  1.256918
2013-01-22  0.352269  1.428700  0.987922  1.366497 -0.135692
2013-01-09  0.220678  1.521160 -0.515815  1.216148  1.226532
2013-01-23 -0.893382  1.798994 -1.020458 -0.693708  0.307356
2013-01-05 -0.140795  2.017113 -0.308425 -0.585616 -0.412642

In [105]:
df["D"]

2013-01-01    0.476068
2013-01-02   -1.588528
2013-01-03    0.647887
2013-01-04   -1.510210
2013-01-05   -0.585616
2013-01-06    1.446361
2013-01-07   -2.113504
2013-01-08   -0.408756
2013-01-09    1.216148
2013-01-10    0.864345
2013-01-11    2.548139
2013-01-12    0.160845
2013-01-13   -0.784211
2013-01-14    0.016866
2013-01-15   -1.663274
2013-01-16    0.794382
2013-01-17    0.329675
2013-01-18   -1.765442
2013-01-19   -0.298426
2013-01-20   -1.777833
2013-01-21   -0.767967
2013-01-22    1.366497
2013-01-23   -0.693708
2013-01-24    0.403497
2013-01-25    0.815398
Freq: D, Name: D, dtype: float64

In [109]:
df[0:24:6]

A         B         C         D         E
2013-01-01  0.107576  0.750734  0.185972  0.476068  0.605057
2013-01-07 -1.342726  0.438657  0.582202 -2.113504  1.655421
2013-01-13 -0.058406 -0.200156 -1.435979 -0.784211  1.204111
2013-01-19 -0.830587 -0.466824 -2.063527 -0.298426  0.648740

# **R**